apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "pythonapp"
        dapr.io/enable-api-logging: "true"
        dapr.io/volume-mounts: "cert-volume:/tmp/certs"
        dapr.io/env: "SSL_CERT_DIR=/tmp/certs"
    spec:
      containers:
        - name: python
          image: docker.io/shubham1172/dapr-python-app:windows
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: "1Gi"
      volumes:
        - name: cert-volume
          secret:
            secretName: https-cert
      nodeSelector:
        kubernetes.io/os: windows
